apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
      - name: hospital-app
        image: joseC2209/springuma-hospital:latest
        
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  type: NodePort
  selector:
    app: hospital
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080